FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
ENV FLASK_APP=app
CMD ["gunicorn","-b","0.0.0.0:8000","app:create_app()","-w","2","-k","gthread"]
