version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: appzero
      POSTGRES_PASSWORD: appzero
      POSTGRES_DB: appzero
    volumes: [db:/var/lib/postgresql/data]
  redis:
    image: redis:7
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    env_file: ../.env
    depends_on: [db, redis]
    ports: ["8000:8000"]
  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.worker
    env_file: ../.env
    depends_on: [redis, db]
  nginx:
    image: nginx:alpine
    depends_on: [api]
    ports: ["5173:80"]
    volumes:
      - ../docker/nginx.conf:/etc/nginx/nginx.conf:ro
volumes: { db: {} }
